# companies having JS

gsoc2023 = "Rocket.chat,GRAME,cBioPortal for Cancer Genomics,Purr Data,XWiki,Processing Foundation,Jenkins,AOSSIE,R project for statistical computing,Python Software Foundation,Mayor's Office of New Urban Mechanics,LibreHealth,Wagtail,Internet Archive,Society for Arts and Technology (SAT),52°North Spatial Information Research GmbH,National Resource for Network Biology (NRNB),Internet Health Report,Mathesar,DBpedia,Plone Foundation,OpenMRS,OpenStreetMap,International Catrobat Association,OWASP Foundation,INCF,MIT App Inventor,Open Technologies Alliance - GFOSS,OpenWISP,Department of Biomedical Informatics, Emory University,Postman,caMicroscope,OSGeo (Open Source Geospatial Foundation),Wikimedia Foundation,MariaDB,GitLab,Submitty,Stratosphere Laboratory, Czech Technical University in Prague,Apertium,Open Chemistry,freifunk,PostgreSQL,Drupal Association,Learning Equality,CircuitVerse.org,Ceph,Creative Commons,The Honeynet Project,Chromium,Cockpit Project,Qdrant,AboutCode,openSUSE Project,Sugar Labs,BRL-CAD,omegaUp,Oppia Foundation,Zulip,The Palisadoes Foundation,The NetBSD Foundation,Git,JdeRobot,The ENIGMA Team,OpenCV,Rizin,FreeType,gprMax,The ns-3 Network Simulator Project,Software and Computational Systems Lab at LMU Munich,The JPF team"
gsoc2022 = "Electron,Neutralinojs,Rocket.chat,cBioPortal for Cancer Genomics,GRAME,Joplin,Purr Data,XWiki,Processing Foundation,Jenkins,AOSSIE,Cuneiform Digital Library Initiative (CDLI),Orcasound,52°North Spatial Information Research GmbH,AboutCode,Casbin,Ceph,CHAOSS,Chromium,CircuitVerse.org,DBpedia,Department of Biomedical Informatics, Emory University,Drupal Association,freifunk,GitLab,INCF,International Catrobat Association,Internet Health Report,Jitsi,Joomla!,Learning Equality,LibreHealth,MariaDB,Mathesar,Matrix.org,Mayor's Office of New Urban Mechanics,MIT App Inventor,Mixxx,moja global,National Resource for Network Biology (NRNB),Open Bioinformatics Foundation (OBF),Open Chemistry,Open Technologies Alliance - GFOSS,OpenMRS,OpenStreetMap,OpenWISP,OSGeo (Open Source Geospatial Foundation),OWASP Foundation,Plone Foundation,Polypheny,PostgreSQL,Public Lab,Python Software Foundation,R project for statistical computing,Responsible AI and Human Centred Technology,Society for Arts and Technology (SAT),Software Heritage,Submitty,The Honeynet Project,Wagtail,Wikimedia Foundation,openSUSE Project,Sugar Labs,BRL-CAD,omegaUp,Oppia Foundation,Our World In Data,The Palisadoes Foundation,Zulip,Git,The NetBSD Foundation,Haskell.org,JdeRobot,syslog-ng,The ENIGMA Team,OpenCV,Rizin,FreeType,MZmine,The ns-3 Network Simulator Project,Flashrom,The JPF team"
gsoc2021 = "GFOSS - Open Technology Alliance,Shaka Player,Ceph,Sugar Labs,XWiki,Digital Impact Alliance (DIAL) at UN Foundation,52°North GmbH,Open Genome Informatics,AOSSIE,Internet Archive,OpenCV,Cuneiform Digital Library Initiative (CDLI),AboutCode,Accord Project,AnkiDroid,Apertium,caMicroscope,Casbin,Chromium,CircuitVerse.org,DBpedia,Debian,FOSSology,FrameNet Brasil (UFJF),Genome Assembly and Annotation,GNOME Foundation,Hydra Ecosystem,INCF,International Catrobat Association,Joomla!,Joplin,Learning Equality,LibreHealth,Matrix.org,Mayor's Office of New Urban Mechanics (City of Boston),Media Cloud,MediaPipe,MetaCall,MGGG Redistricting Lab,MIT App Inventor,National Resource for Network Biology (NRNB),NumFOCUS,Open Bioinformatics Foundation,Open Chemistry,openastronomy,OpenMined,OpenMRS,OpenStreetMap,OpenWISP,Orcasound,OSGeo - Open Source Geospatial Foundation,OWASP Foundation,Polypheny,Postman,Public Lab,Purr Data,React Native Elements,TensorFlow,The Palisadoes Foundation,The R Project for Statistical Computing,Wikimedia Foundation,Xfce,Processing Foundation,BRL-CAD,Elm Tooling,Kiwix,Open Roberta,vitrivr,Godot Engine,GRR Rapid Response,JabRef e.V.,Oppia Foundation,Zulip,LabLua,FreeBSD Project,Git,strace,The NetBSD Foundation,Haskell.org,JdeRobot - Universidad Rey Juan Carlos,syslog-ng,Rocket.Chat,The ENIGMA Team,Java PathFinder,FreeType,Rizin,gprMax,Plan 9 Foundation"
gsoc2020 = "Moira,Percona,Ceph Foundation,GPAC,XWiki,Open Genome Informatics,Jenkins project,52° North GmbH,webpack,GDevelop,Rocket.Chat,Processing Foundation,OpenCV,Canadian Centre for Computational Genomics,Open Roberta,Postman,Orcasound,AboutCode.org,Accord Project,Amahi,AnitaB.org Open Source,AOSSIE,BeagleBoard.org,caMicroscope,Casbin,CHAOSS,CircuitVerse.org,CiviCRM,Creative Commons,DBpedia,Debian,Digital Impact Alliance (DIAL) at UN Foundation,Drupal,FOSSology,FrameNet Brasil (UFJF),GraphQL Foundation,INCF,Inclusive Design Institute,Internet Archive,Kiwix,LibreHealth,Liquid Galaxy project,Matrix,MGGG Redistricting Lab,MIT App Inventor,Mixxx,Mozilla,National Resource for Network Biology (NRNB),NumFOCUS,Open Bioinformatics Foundation (OBF),Open Chemistry,OpenAstronomy,OpenEMR,OpenMRS,OpenRefine,OpenStreetMap,openSUSE Project,OpenWISP,OWASP Foundation,Purr Data,R Project for Statistical Computing,Submitty,Sugar Labs,The GNU Project,Wikimedia Foundation,MacPorts,Zulip,OpenMined,LabLua,FreeBSD Project,Git,BRL-CAD,Haskell.org,Hazelcast,JdeRobot - Universidad Rey Juan Carlos,syslog-ng,The Java Pathfinder Team,Homebrew,Kapitan,FreeType,Radare,Fedora Project,MZmine,Cuneiform Digital Library Initiative (CDLI)"
gsoc2019 = "Moira,aimacode,XWiki,BRL-CAD,Jenkins project,52°North Initiative for Geospatial Open Source Software GmbH,Rocket.Chat,InterMine,The Processing Foundation,webpack,The Center for Connected Learning and Computer-Based Modeling,Percona,Canadian Center for Computational Genomics,Purr Data,Open Roberta,Software and Computational Systems Lab at LMU Munich,CLiPS, University of Antwerp,AboutCode.org,AOSSIE - Australian Open Source Software Innovation and Education,BeagleBoard.org,cBioPortal for Cancer Genomics,CBMI@UTHSC,CCExtractor Development,Center for Research in Open Source Software at UC Santa Cruz,CHAOSS,CircuitVerse.org,CiviCRM,Computational Biology @ University of Nebraska-Lincoln,Creative Commons,DBpedia,Debian,Digital Impact Alliance,Drupal,FOSDEM,FOSSASIA,FrameNet Brasil at the Federal University of Juiz de Fora,Genes, Genomes and Variation,GNOME,Hydra Ecosystem,INCF,Institut für Angewandte Informatik (InfAI) e.V.,Internet Archive,Internet Systems Consortium,Joomla,Kiwix,KNIME,LibreHealth,Matrix.org,MetaBrainz Foundation Inc,MIT App Inventor,Moodle,Mozilla,Named Data Networking Project,National Resource for Network Biology (NRNB),NumFOCUS,Open Bioinformatics Foundation,Open Chemistry,Open Technologies Aliance - GFOSS,OpenMRS,OpenStreetMap,OpenWISP,Oppia Foundation,OWASP Foundation,Performance Co-Pilot,phpMyAdmin,Public Lab,R project for statistical computing,Salesforce,Software Heritage,Submitty,Sugar Labs,The Eclipse Foundation,UCSC Xena,Wikimedia Foundation,xpra,Zulip Open Source Project,LabLua,Godot Engine,MacPorts,MBDyn - Multibody Dynamics,The Vega Project at the University of Washington,API Client Tools at Google,FreeBSD,Gentoo Foundation,strace,Haskell.Org,JdeRobot - Universidad Rey Juan Carlos,syslog-ng,OpenCV,Neovim,Kapitan,FreeType,Fedora Project,gprMax,Cuneiform Digital Library Initiative (CDLI),ZynAddSubFX,The Java Pathfinder Team"
gsoc2018 = "GFOSS - Open Technologies Alliance,The Vega Visualization Tools by the UW Interactive Data Lab,Rspamd,Jenkins project,XWiki,Plone,52° North Initiative for Geospatial Open Source Software GmbH,Rocket.Chat,Jitsi,The Processing Foundation,webpack,InterMine,Neovim,Purr Data,Open Roberta Lab,Software and Computational Systems Lab at LMU Munich,CLiPS, University of Antwerp,Debian Project,aimacode,Amahi,BeeWare Project,Berkman Klein Center for Internet & Society at Harvard University,Center for Research In Open Source Software (CROSS) at UC Santa Cruz,CHAOSS: Community Health Analytics Open Source Software,Classical Language Toolkit,Computational Biology @ University of Nebraska-Lincoln,Conversations.im,Digital Impact Alliance,Drupal,Earth Science Information Partners (ESIP),FOSSASIA,freifunk,GNOME,INCF,Inclusive Design Institute,Internet Archive,Joomla!,languagetool.org,LEAP Encryption Access Project,LibreHealth,MetaBrainz Foundation Inc.,Moodle,Mozilla,National Resource for Network Biology (NRNB),NumFOCUS,Open Bioinformatics Foundation,Open Chemistry,Open Source Robotics Foundation,OpenMRS,OpenStreetMap,OpenWISP,OpnTec,Oppia Foundation,OWASP Foundation,P2PSP.org,PEcAn Project,Performance Co-Pilot,phpBB Forum Software,phpMyAdmin,Probot,Public Lab,Quill.org,R project for statistical computing,Read the Docs,Space @ Virginia Tech,Stemformatics,Stony Brook University Biomedical Informatics,Streetmix,Sugar Labs,Systers Community,TEAMMATES @ National University of Singapore,The Center for Connected Learning and Computer-Based Modeling,The Eclipse Foundation,UCSC Xena,Wikimedia Foundation,WorldBrain.io - Verifying the Internet,xpra.org,Zulip,AOSSIE - Australian Open Source Software Innovation and Education,openSUSE,Submitty,The MacPorts Project,Genes, Genomes and Variation,OpenSIPS,FreeBSD,Gentoo Foundation,Git,strace,The Libreswan Project,Free UK Genealogy,Haskell.org,JdeRobot - Universidad Rey Juan Carlos,The syslog-ng project.,Inria Foundation,PMD,Eta,The Java Pathfinder Team,FreeType,Fedora Project,JGraphT"

companies = gsoc2018 + gsoc2019 + gsoc2020 + gsoc2021 + gsoc2022 + gsoc2023
companies = companies.split(',')
for i in range(len(companies)):
    companies[i] = companies[i].strip().capitalize()

most_frequent = {}
for company in companies:
    if most_frequent.get(company, None) == None:
        most_frequent[company] = 1
    else:
        most_frequent[company] += 1

topcompanies = sorted(most_frequent.items(), key=lambda x:x[1], reverse=True)
for company in topcompanies:
    print(company[0]," - ",company[1])

print(len(topcompanies))